module.exports = [
  {
    title: "A General Safety Framework for Autonomous Manipulation in Human Environments",
    authors: "J. Thumm, J. Balletshofer, L. Maglanoc, L. Muschal, M. Althoff",
    venue: "IEEE Transactions on Robotics",
    type: "Journal",
    year: 2026,
    tag: "safe-ai",
    url: "http://arxiv.org/abs/2412.10180",
    img: "/assets/img/safety_framework_thumbnail.jpg",
  },
  {
    title: "From Demonstrations to Safe Deployment: Path-Consistent Safety Filtering for Diffusion Policies",
    authors: "R. Römer, J. Balletshofer, J. Thumm, M. Pavone, A. P. Schoellig, M. Althoff",
    venue: "IEEE Int. Conf. on Robotics and Automation (ICRA)",
    type: "Conference",
    year: 2026,
    tag: "embodied-ai",
    url: "http://arxiv.org/abs/2511.06385",
    img: "/assets/img/embodiedAI_thumbnail.jpg",
  },
  {
    title: "Multi-Objective Causal Bayesian Optimization",
    authors: "S. Bhatija, P.-D. Zuercher, J. Thumm, T. Bohné",
    venue: "Int. Conf. on Machine Learning (ICML)",
    type: "Conference",
    year: 2025,
    tag: "other",
    url: "https://openreview.net/forum?id=sDGafRLNQa",
    img: "/assets/img/mo_cbo_thumbnail.jpg",
  },
  {
    title: "Excluding the Irrelevant: Focusing Reinforcement Learning through Continuous Action Masking",
    authors: "R. Stolz, H. Krasowski, J. Thumm, M. Eichelbeck, P. Gassert, M. Althoff",
    venue: "Conf. on Neural Information Processing Systems (NeurIPS)",
    type: "Conference",
    year: 2024,
    tag: "embodied-ai",
    url: "https://openreview.net/forum?id=yVzWlFhpRW",
    img: "/assets/img/action_masking_results_thumbnail.jpg",
  },
  {
    title: "Text2Interaction: Establishing Safe and Preferable Human-Robot Interaction",
    authors: "J. Thumm, C. Agia, M. Pavone, M. Althoff",
    venue: "Annual Conf. on Robot Learning (CoRL)",
    type: "Conference",
    year: 2024,
    tag: "personalized-ai",
    url: "https://openreview.net/forum?id=s0VNSnPeoA",
    website: "https://sites.google.com/view/text2interaction",
    img: "/assets/img/personalizedAI_thumbnail.jpg",
  },
  {
    title: "Human-Robot Gym: Benchmarking Reinforcement Learning in Human-Robot Collaboration",
    authors: "J. Thumm, F. Trost, M. Althoff",
    venue: "IEEE Int. Conf. on Robotics and Automation (ICRA)",
    type: "Conference",
    year: 2024,
    tag: "embodied-ai",
    url: "https://ieeexplore.ieee.org/abstract/document/10610705/",
    img: "/assets/img/hrgym_thumbnail.jpg",
  },
  {
    title: "Provably Safe Reinforcement Learning: Conceptual Analysis, Survey, and Benchmarking",
    authors: "H. Krasowski, J. Thumm, M. Müller, L. Schäfer, X. Wang, M. Althoff",
    venue: "Transactions on Machine Learning Research (TMLR)",
    type: "Journal",
    year: 2023,
    tag: "embodied-ai",
    url: "https://openreview.net/forum?id=mcN0ezbnzO",
    img: "/assets/img/provably_safe_rl_structure_thumbnail.jpg",
  },
  {
    title: "Reducing Safety Interventions in Provably Safe Reinforcement Learning",
    authors: "J. Thumm, G. Pelat, M. Althoff",
    venue: "IEEE/RSJ Int. Conf. on Intelligent Robots and Systems (IROS)",
    type: "Conference",
    year: 2023,
    tag: "embodied-ai",
    url: "https://ieeexplore.ieee.org/abstract/document/10342464/",
    img: "/assets/img/reducing_failsafe_robot_thumbnail.jpg",
  },
  {
    title: "Approximate First-Passage Time Distributions for Gaussian Motion and Transportation Models",
    authors: "M. Reith-Braun, F. Pfaff, J. Thumm, U. D. Hanebeck",
    venue: "Int. Conf. on Information Fusion (FUSION)",
    type: "Conference",
    year: 2023,
    tag: "other",
    url: "https://ieeexplore.ieee.org/abstract/document/10224164",
    img: "/assets/img/first_passage_time_thumbnail.jpg",
  },
  {
    title: "SaRA: A Tool for Safe Human–Robot Coexistence and Collaboration through Reachability Analysis",
    authors: "S. Schepp, J. Thumm, S. B. Liu, M. Althoff",
    venue: "IEEE Int. Conf. on Robotics and Automation (ICRA)",
    type: "Conference",
    year: 2022,
    tag: "safe-ai",
    url: "https://ieeexplore.ieee.org/abstract/document/9811952",
    img: "/assets/img/SARA_thumbnail.jpg",
  },
  {
    title: "Provably Safe Deep Reinforcement Learning for Robotic Manipulation in Human Environments",
    authors: "J. Thumm, M. Althoff",
    venue: "IEEE Int. Conf. on Robotics and Automation (ICRA)",
    type: "Conference",
    year: 2022,
    tag: "safe-ai",
    doi: "10.1109/ICRA46639.2022.9811698",
    img: "/assets/img/hri_dark_thumbnail.jpg",
  },
  {
    title: "Mixture of Experts of Neural Networks and Kalman Filters for Optical Belt Sorting",
    authors: "J. Thumm, M. Reith-Braun, F. Pfaff, U. D. Hanebeck, M. Flitter, G. Maier, R. Gruna, T. Langle, A. Bauer, H. Kruggel-Emden",
    venue: "IEEE Transactions on Industrial Informatics",
    type: "Journal",
    year: 2022,
    tag: "other",
    doi: "10.1109/TII.2021.3114282",
    img: "/assets/img/optical_belt_sorter_thumbnail.jpg",
  },
  {
    title: "A Novel Approach to Label Road Defects in Video Data: Semi-Automated Video Analysis",
    authors: "J. Thumm, J. Masino, M. Knoche, F. Gauterin, M. Reischl",
    venue: "International Journal on Smart Sensing and Intelligent Systems",
    type: "Journal",
    year: 2020,
    tag: "other",
    url: "https://reference-global.com/article/10.21307/ijssis-2020-007",
    img: "/assets/img/mercedes_pothole_thumbnail.jpg",
  },
  {
    title: "Characterization of Road Condition with Data Mining Based on Measured Kinematic Vehicle Parameters",
    authors: "J. Masino, J. Thumm, G. Levasseur, M. Frey, F. Gauterin, R. Mikut, M. Reischl",
    venue: "Journal of Advanced Transportation",
    type: "Journal",
    year: 2018,
    tag: "other",
    doi: "10.1155/2018/8647607",
    img: "/assets/img/damage_events_thumbnail.jpg",
  },
  {
    title: "Multiple Vehicle Fusion for a Robust Road Condition Estimation Based on Vehicle Sensors and Data Mining",
    authors: "J. Hofmockel, J. Masino, J. Thumm, E. Sax, F. Gauterin",
    venue: "Cogent Engineering",
    type: "Journal",
    year: 2018,
    tag: "other",
    doi: "10.1080/23311916.2018.1449428",
    img: "/assets/img/road_condition_thumbnail.jpg",
  },
  {
    title: "Learning from the Crowd: Road Infrastructure Monitoring System",
    authors: "J. Masino, J. Thumm, M. Frey, F. Gauterin",
    venue: "Journal of Traffic and Transportation Engineering",
    type: "Journal",
    year: 2017,
    tag: "other",
    doi: "10.1016/j.jtte.2017.06.003",
    img: "/assets/img/road_condition_thumbnail.jpg",
  },
  {
    title: "Parking Events Derived From Trip Data from MiD2008",
    authors: "J. Huber, J. Höffer, J. Thumm, C. Weinhardt",
    venue: "Dataset",
    type: "Dataset",
    year: 2019,
    tag: "other",
    doi: "10.5445/IR/1000098024",
    img: "/assets/img/parking_events_thumbnail.jpg",
  },
];
